services:
  web:
    build:
      context: .
    container_name: user-service
    env_file:
      - .env
    command: >
      sh -c "
        uv run manage.py runserver 0.0.0.0:7011
      "
    volumes:
      - .:/app
      - venv:/app/.venv
    ports:
      - "7011:7011"
    restart: unless-stopped
  
  user_consumer:
    build:
      context: .
    container_name: user-consumer
    env_file:
      - .env
    command: uv run manage.py consume_kafka
    volumes:
      - .:/app
      - venv:/app/.venv
    restart: unless-stopped


volumes:
  venv: